name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml

      - name: Install Package
        run: |
          pnpm install

      - name: Prettier
        run: pnpm prettier

      - name: Lint
        run: pnpm lint